### ISSUE TITLE
golint: should not use dot imports (workarounds?)

### ISSUE THREAD

**Issue by ear** [tj/go-debug#16]
It [looks like](https://github.com/golang/lint/issues/179#issuecomment-160277781) [golint](https://github.com/golang/lint) will not implement options to disable particular checks anytime soon. How do you handle the omnipresent linting error:

```
at line __, character __, file ____.go: should not use dot imports
```

Is there some kind of other annotation one can use to enable this "natural" use for the debug package that I am missing? What do you usually do?

**Comment by mwmahlberg** [comment]
Simply import as below and your glint problem will vanish:

```go
package main

import (
    dbg "github.com/tj/go-debug"
)

func main() {
    var debug = dbg.Debug("main")
    debug("foo")
}
```

**Comment by ear** [comment]
That did not occur to me, thank you!

**Comment by mwmahlberg** [comment]
So you can close this issue, right? ;)

**Comment by ear** [comment]
Sure.
